name: color_picker_example
description: Two examples of how to use the FlexColorPicker package.
version: 2.0.0-nullsafety.5
publish_to: 'none'
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flex_color_picker:
    path: ../

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^0.13.1+1

  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
